package org.opensearch.commons.notifications

/**
 * Class containing Internal constants like JSON tags and defaults.
 */
object NotificationConstants {
    const val CONFIG_ID_TAG = "config_id"
    const val CONFIG_ID_LIST_TAG = "config_id_list"
    const val EVENT_ID_TAG = "event_id"
    const val EVENT_ID_LIST_TAG = "event_id_list"
    const val EMAIL_ACCOUNT_ID_TAG = "email_account_id"
    const val REFERENCE_ID_TAG = "reference_id"
    const val CHANNEL_ID_LIST_TAG = "channel_id_list"
    const val CONFIG_NAME_TAG = "config_name"
    const val CONFIG_TYPE_TAG = "config_type"
    const val CONFIG_TAG = "config"
    const val EVENT_TAG = "event"
    const val EVENT_SOURCE_TAG = "event_source"
    const val FEATURE_TAG = "feature"
    const val THREAD_CONTEXT_TAG = "context"
    const val CHANNEL_MESSAGE_TAG = "channel_message"
    const val TEXT_DESCRIPTION_TAG = "text_description"
    const val HTML_DESCRIPTION_TAG = "html_description"
    const val ATTACHMENT_TAG = "attachment"
    const val FILE_NAME_TAG = "file_name"
    const val FILE_ENCODING_TAG = "file_encoding"
    const val FILE_DATA_TAG = "file_data"
    const val FILE_CONTENT_TYPE_TAG = "file_content_type"
    const val RECIPIENT_TAG = "recipient"
    const val RECIPIENT_LIST_TAG = "recipient_list"
    const val EMAIL_RECIPIENT_STATUS_TAG = "email_recipient_status"
    const val EMAIL_GROUP_ID_LIST_TAG = "email_group_id_list"
    const val STATUS_CODE_TAG = "status_code"
    const val STATUS_TEXT_TAG = "status_text"
    const val DELIVERY_STATUS_TAG = "delivery_status"
    const val NAME_TAG = "name"
    const val DESCRIPTION_TAG = "description"
    const val IS_ENABLED_TAG = "is_enabled"
    const val FEATURE_LIST_TAG = "feature_list"
    const val TITLE_TAG = "title"
    const val SEVERITY_TAG = "severity"
    const val TAGS_TAG = "tags"
    const val URL_TAG = "url"
    const val HEADER_PARAMS_TAG = "header_params"
    const val TOPIC_ARN_FIELD = "topic_arn"
    const val ROLE_ARN_FIELD = "role_arn"
    const val HOST_TAG = "host"
    const val PORT_TAG = "port"
    const val METHOD_TAG = "method"
    const val FROM_ADDRESS_TAG = "from_address"
    const val UPDATED_TIME_TAG = "last_updated_time_ms"
    const val CREATED_TIME_TAG = "created_time_ms"
    const val TENANT_TAG = "tenant"
    const val CONFIG_LIST_TAG = "config_list"
    const val EVENT_LIST_TAG = "event_list"
    const val FEATURE_CONFIG_LIST_TAG = "feature_channel_list"
    const val DELETE_RESPONSE_LIST_TAG = "delete_response_list"
    const val FROM_INDEX_TAG = "from_index"
    const val MAX_ITEMS_TAG = "max_items"
    const val SORT_FIELD_TAG = "sort_field"
    const val SORT_ORDER_TAG = "sort_order"
    const val FILTER_PARAM_LIST_TAG = "filter_param_list"
    const val STATUS_LIST_TAG = "status_list"
    const val START_INDEX_TAG = "start_index"
    const val TOTAL_HITS_TAG = "total_hits"
    const val TOTAL_HIT_RELATION_TAG = "total_hit_relation"
    const val QUERY_TAG = "query"
    const val COMPACT_TAG = "compact"
    const val CONFIG_TYPE_LIST_TAG = "config_type_list"
    const val PLUGIN_FEATURES_TAG = "plugin_features"

    const val DEFAULT_MAX_ITEMS = 1000
}
